# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FIR_Response = GraphicsLayoutWidget(self.centralwidget)
        self.FIR_Response.setGeometry(QtCore.QRect(10, 10, 470, 510))
        self.FIR_Response.setObjectName("FIR_Response")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(10, 650, 470, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Start.setFont(font)
        self.Start.setObjectName("Start")
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(10, 730, 470, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.Stop.setFont(font)
        self.Stop.setObjectName("Stop")
        self.Original_Data = GraphicsLayoutWidget(self.centralwidget)
        self.Original_Data.setGeometry(QtCore.QRect(500, 10, 690, 240))
        self.Original_Data.setObjectName("Original_Data")
        self.Spectrum = GraphicsLayoutWidget(self.centralwidget)
        self.Spectrum.setGeometry(QtCore.QRect(500, 280, 690, 240))
        self.Spectrum.setObjectName("Spectrum")
        self.Filtered_Data = GraphicsLayoutWidget(self.centralwidget)
        self.Filtered_Data.setGeometry(QtCore.QRect(500, 550, 690, 240))
        self.Filtered_Data.setObjectName("Filtered_Data")
        self.BPM = QtWidgets.QLabel(self.centralwidget)
        self.BPM.setGeometry(QtCore.QRect(10, 550, 470, 60))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.BPM.setFont(font)
        self.BPM.setStyleSheet("")
        self.BPM.setAlignment(QtCore.Qt.AlignCenter)
        self.BPM.setObjectName("BPM")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PPG"))
        self.Start.setText(_translate("MainWindow", "START"))
        self.Stop.setText(_translate("MainWindow", "STOP"))
        self.BPM.setText(_translate("MainWindow", "Average Heart Beat: 0.00 bpm"))
from pyqtgraph import GraphicsLayoutWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
